# Generated by Django 5.1.2 on 2024-12-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('semester', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
                ('sks', models.PositiveIntegerField(default=2)),
            ],
        ),
    ]
